version: '3'

networks:
    backend:
      driver: bridge

services:
    web:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "8000:8000"
        restart: unless-stopped
        networks:
            - backend
        depends_on: 
            - redis

    postgres:
        build:
            context: ./docker/postgres
        volumes:
            - ./data/db/postgres:/var/lib/postgresql/data
            - /tmp/postgres_log:/tmp/postgres_log
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=golangdb
            - POSTGRES_USER=golang
            - POSTGRES_PASSWORD=golang
        networks:
            - backend

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - backend